Finished ZUC256 without MAC
Nugine/zuc pull request #3
Opened 2024-12-10 02:16 UTC by Xerxes-zhz

- Finished ZUC256 without MAC, but I changed the project structure a lot. Maybe we should check it if it's an acceptable restructure.
-  I refactored the ZUC algorithm module into a public module and restructured ZUC128, so the module could support both ZUC256 and ZUC128. 
- Additionally, some variable names and conventions might not be optimal. I would appreciate any suggestions for improvement.

2024-12-10 04:31 UTC, Nugine requested changes
主要建议
+ review 中提出的修改要求
+ CI 报错，主要为 lint，根据提示修改
+ MAC 部分的 todo 需解决

2024-12-10 04:31 UTC, Nugine commented on README.md
> +- **ZUC 256**:[ZUC256-version1.1](http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020180416526664982687.pdf)
额外发现了两篇关于 ZUC-256 的更新
+ http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020220926381349696866.pdf
+ http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020230201389233346416.pdf

可以看下在密码学安全性上有没有实现的必要。
若无必要，也可列入参考并标记为暂未实现。

2024-12-10 04:31 UTC, Nugine commented on src/lib.rs
> +mod zuc_data;
mod zuc_data 可取消。

仅被 zuc128 引用的常量合并到 mod zuc128。
仅被 zuc256 引用的常量合并到 mod zuc256。
若 zuc256 引用了 zuc128 的常量，则可设置为 pub(crate)，直接从 zuc128 导入。这样表达历史上的关系更清楚一些。

2024-12-10 04:31 UTC, Nugine commented on src/utils.rs
> +}
L1 和 L2 并非通用工具函数，可合并到 zuc 公共实现。

2024-12-10 04:31 UTC, Nugine commented on src/zuc.rs
> +/// ZUC keystream generator
所有逻辑上有区分的 item 之间应空行。
需检查其他未空行的地方。

2024-12-10 04:31 UTC, Nugine commented on src/zuc128.rs
> +    zuc: ZUC,
`zuc.zuc` 有点奇怪，可以写成 `zuc.core` 或其他命名

2024-12-10 04:31 UTC, Nugine commented on src/zuc.rs
> +    pub fn init(&mut self, s: [u32; 16]) {
这里无需复制 s，由于 pub(crate) s，外面初始化时先 zeroed 创建，再直接覆盖 zuc.s 就行了

2024-12-10 04:31 UTC, Nugine commented on src/zuc256.rs
> +/// ZUC256 keystream generator
此处类型文档需列出 ZUC256 的参考标准

2024-12-10 04:31 UTC, Nugine commented on tests/zuc256.rs
> +    }
示例测试向量来自于 zuc256 文档，最好合并到 mod zuc256 作为单元测试

2024-12-10 13:59 UTC, ouuan commented
统一改成 `Zuc128`, `Zuc256`，而不是 `ZUC256` 吧，`aes` 是这样的

2024-12-10 14:04 UTC, Nugine commented
> 统一改成 `Zuc128`, `Zuc256`，而不是 `ZUC256` 吧，`aes` 是这样的，标准库里也有 `IpAddr` 这种例子。全大写像是 constant

可以，跟随先例，参考 `aes::Aes128`。不过这也是个常见命名问题，`XMLHttpRequest` vs `XmlHttpRequest`。

2024-12-11 07:42 UTC, Nugine commented on README.md
> +- **Zuc 256 New Initialization**:[Zuc256-new-initialization](http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020230201389233346416.pdf)
这些倒是不用改成 Zuc，标准文件里写的是 ZUC

2024-12-11 07:42 UTC, Nugine commented on README.md
> +# Zuc
这个是 crate 名称，不用改

2024-12-11 09:41 UTC, Nugine commented on src/zuc256.rs
> +}
concat_bits 能否更高效？
提示：可参考 gmssl 的实现

2024-12-11 09:43 UTC, Nugine requested changes
我按个人偏好改了一些地方

剩余的所需修改
+ 优化 concat_bits
+ 决定是否将 mac 实现拆分到另一 PR

2024-12-11 13:41 UTC, Xerxes-zhz commented on src/zuc256.rs
> +}
这里是为了优先提交, 方便大家合并,  直接AI生成出来就提交了, 我感觉可以先开个develop分支, 合并的时候压力也小一点,也好保持main分支的干净

2024-12-11 15:02 UTC, Nugine commented on src/zuc256.rs
> +    pub fn new(k: &[u8; 32], iv: &[u8; 25]) -> Self {
IV 是 184 bits (u8x23)，这里似乎不对

https://github.com/guanzhi/GmSSL/blob/34fa519dc0f94a9a3995d9daf09c84cdac37abd8/src/zuc.c#L524-L531

2024-12-11 15:04 UTC, Nugine commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
如果参考的 gmssl 实现正确的话，这里无需 `& 0x7F`

2024-12-11 15:09 UTC, Nugine commented
没找到其他 Rust ZUC256 实现，也没找到除了 IV 0x00 和 IV 0xFF 以外的测试用例。
坏消息：测试不能捕获有关 IV 的错误。
好消息：我们这是整个 Rust 生态中第一个 ZUC256 实现。

2024-12-11 15:35 UTC, Xerxes-zhz commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
不过测试用例确实没有覆盖到这种情况

2024-12-11 15:37 UTC, Nugine commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
gmssl 的写法里，IV17~IV24 都只有低 6 位

https://github.com/guanzhi/GmSSL/blob/34fa519dc0f94a9a3995d9daf09c84cdac37abd8/src/zuc.c#L524-L531

2024-12-11 15:44 UTC, Xerxes-zhz commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
似乎和3篇论文都不一样

2024-12-11 15:49 UTC, Nugine commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
ZUC256 v1.1 那篇文档里有

![图片](https://github.com/user-attachments/assets/dd4ac6b2-f3bc-41e9-92c5-309eaa8681c2)

![图片](https://github.com/user-attachments/assets/ad9d950f-c3d2-4f9a-a610-bba144809510)

2024-12-11 16:34 UTC, Xerxes-zhz commented on src/zuc256.rs
> +    (u32::from(a) << 23) | (u32::from(b & 0x7F) << 16) | (u32::from(c) << 8) | u32::from(d)
哦哦, 我一下脑子没转过来, 这里有个IV[17..=22]预处理, gmssl是少传了1个IV再拆开了

2024-12-12 07:36 UTC, Nugine approved these changes

2024-12-12 07:49 UTC, merged