feat: 128-EIA3 implementation
Nugine/zuc pull request #8
Opened 2024-12-24 07:13 UTC by Xerxes-zhz

2024-12-24 07:57 UTC, Nugine requested changes
感谢贡献！优化后的活动流程将进行至多三轮 review，此后未发现或未完成的问题将由我直接提交修改。

本次为第一轮 review，建议如下：
+ 按要求修改格式与文档相关问题
+ 尝试完成有关空间复杂度和内存分配的优化

2024-12-24 07:57 UTC, Nugine commented on src/zuc.rs
> -
没必要删空行，可以加个提交 revert 这个删除

2024-12-24 07:57 UTC, Nugine commented on README.md
> -
没必要删空行，可以加个提交 revert 这个删除

2024-12-24 07:57 UTC, Nugine commented on README.md
> +- **128-EIA3**: [GB/T 33133.3-2021](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=C6D60AE0A7578E970EF2280ABD49F4F0)
也加上到 gsma 的链接

2024-12-24 07:57 UTC, Nugine commented on src/eia3_128.rs
> +            println!("{:x} {:x}", x.mac, &mac);
调试代码可删除或注释掉

2024-12-24 07:57 UTC, Nugine commented on src/eia3_128.rs
> +}
能否优化到空间 O(1) 且零次内存分配？

根据先例 (#4)，若此优化最终证明可行，未实现此优化将扣除总奖励额的 10%

2024-12-24 07:57 UTC, Nugine commented on src/eia3_128.rs
> +];
这些 bitmask 查表可能反而更慢了

2024-12-24 10:50 UTC, Xerxes-zhz commented
这个m如果直接用&[u32]似乎更方便一点？

2024-12-24 11:51 UTC, Nugine commented on src/eia3_128.rs
> +    t
能否 32bits (4bytes) 为一组，每次循环处理一组，最后再处理末尾的 bits

2024-12-24 11:57 UTC, Nugine commented on src/eia3_128.rs
> +        mac: &'static u32,
```suggestion
        mac: u32,
```

2024-12-24 14:26 UTC, Xerxes-zhz commented on src/eia3_128.rs
> +    t
这个我考虑了过, 因为我注意到gmssl都是直接处理32位的, 我本来还发了条comment问要不要改这个, 但是详细考虑后删除了

我发现按现在的算法, 似乎使用32位,除了减少3次对bit_mask的重置外, 并不能提高性能, 其他的操作数完全没变, 而且有合并的开销, 同时32位的按位与取最高位bit或许比8位的会慢一点? gmssl使用32位, 我目前认为主要是解决我这里用i/8的定位问题, 我这里每次除一下确实不太好, 但是如果采用计数器来代替, 应该就可以了?

或者每次把m_i取下来左移去和0b1000_0000与

计数器方案如下

```rust
for...{
    if bit_counter == 0 {
        bit_mask = 0b1000_0000;
        if key_counter == 0 {
            next_key = zuc.generate();
        }
    }

  <other code>

 (m[byte_index] & bit_mask) != 0
  
  <other code>

    bit_counter += 1;
    bit_in_byte += 1;

    if bit_in_byte == 8 {
        bit_in_byte = 0;
        byte_index += 1;
        bit_counter = 0; 
        key_counter += 1;
        if key_counter == 4 {
            key_counter = 0;
        }
    }
}
```

2024-12-24 15:31 UTC, Nugine commented on src/eia3_128.rs
> +    t
也可以不合并为 u32，按 4 个 byte 分别处理。
4 bytes 分组主要考虑的是减少高频循环体内部的分支数量，避免分支走向频繁变化，也能减少很多判断指令。同时整个逻辑看起来也会更简单一些。
或者写个简单测试，看看性能有没有差异。

2024-12-24 17:51 UTC, Nugine commented on src/eia3_128.rs
> +    t
初步测量，分组写法比不分组的性能高出8倍以上

2024-12-24 18:21 UTC, Xerxes-zhz commented
我感觉在该思路下优化到极致了, 按32位分块后其实只剩1次, 直接update就好了
然后对分块的部分进行了剪枝和展开, 写出来比想象中漂亮非常多
剩下的可能存在的优化就是把(0..bitlen),bitlen,(bitlen+1..last_update_idx) 3个部分展开, 不过按我这个思路, 我研究了下似乎是没法展开了, 状态没办法无损的传递过去

2024-12-24 18:25 UTC, Xerxes-zhz commented on src/eia3_128.rs
> +    t
是的, 我低估分支判断的性能损耗了, 而且除法和取余确实太吃性能了

2024-12-24 19:00 UTC, Xerxes-zhz commented
新写的这个取索引的我又研究了下, 好像不如直接用idx, 不过这个地方其实可以用uncheck的idx, 你看看需不需要用unsafe吧

2024-12-25 02:56 UTC, Nugine commented on src/eia3_128.rs
> +}
实测结果：
+ 当前写法: 约 80 MiB/s
+ 4bytes分组+合并u32+末尾单独处理: 约 130MiB/s

2024-12-25 02:57 UTC, Nugine commented on src/eia3_128.rs
> +    }
这个测试失败

2024-12-25 03:03 UTC, Nugine reviewed
第二轮 review 结束。我添加了两个测试用例，还有 benchmark。
目前主要围绕 generate_mac 的性能优化，可尝试消除冗余的分支判断。

在第三轮 review 结束前，有任何问题，我会给出必要的提示和思路，但不会完整给出我自己的写法代码。

2024-12-25 07:10 UTC, Xerxes-zhz commented
我尝试了你提出的优化点并做了一些对比, 目前核心逻辑如下在我的机器上是130M/s 和你的机器应该是有性能差距, 我不太确定与目前是否与对照组有性能差距, 我还没有加remainder的逻辑
目前在我的机器上依旧是不合并成u32的性能更高, 我尝试了两种合并方式, 性能都和不合并有差距, 是我的合并方法有问题吗?


```rust
    let mut current_m: u8 = 0;
    let chunks = bitlen / 8;

    let m_iter = m[0..chunks].chunks_exact(4);
    // chunks_exact is 10% faster than chunks 
    // use chunks_exact is 10% faster than for _ in 0..chunks and get m with idx 

    for chunk in m_iter {
        current_key |= (zuc.generate()) as u64;
        for &c in chunk {
            current_m = c;
            // current_m = ((chunk[0] as u32) << 24) | ((chunk[1] as u32) << 16) | ((chunk[2] as u32) << 8) | chunk[3] as u32;
            // current_m = u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
            // (a as u32)<<24|...|d as u32 is 5% faster than from_be_bytes            
            // (use u32 current_key)1 byte per run with u8 is 4% faster than 4 byte per run with u32 
            // (use u64 current_key)1 byte per run with u8 is 20% faster than 4 byte per run with u32 

            for _ in 0..8 {
                if (current_m & 0b1000_0000) != 0 {
                // move data is 5% faster than move mask

                    t ^= (current_key >> 32) as u32;
                }
                current_m <<= 1;
                current_key <<= 1;
                // use u64 is 35% faster than u32 

            }
        }
    }
```

2024-12-25 11:12 UTC, Nugine commented
我大概是这样的写法
```rust
bits = u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
// ...
for _ in 0..32 {
  // ...
  bits <<= 1;
  key <<= 1;
}
```

不过发现我的写法在两个追加测试中的输出结果和你初版写法不一致，却都能通过 5 个标准测试用例。
gm-zuc 甚至无法通过标准测试用例。
我打算和 gmssl 对拍一下，拿个正确答案来测。

我们优先保证正确性，优化不是必需的。

2024-12-25 12:19 UTC, Xerxes-zhz commented
我昨天没过用例是因为等于bitlen的时候m已经用完了，放在循环外会panic，不过第一版方案确实没有这个问题

2024-12-25 12:35 UTC, Xerxes-zhz commented
> 我大概是这样的写法
> ```rust
> bits = u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
> // ...
> for _ in 0..32 {
>   // ...
>   bits <<= 1;
>   key <<= 1;
> }
> ```
> 
> 不过发现我的写法在两个追加测试中的输出结果和你初版写法不一致，却都能通过 5 个标准测试用例。
> gm-zuc 甚至无法通过标准测试用例。
> 我打算和 gmssl 对拍一下，拿个正确答案来测。
> 
> 我们优先保证正确性，优化不是必需的。

你这个方案用我目前的内部写法，在我的机器上，会比直接索引4个元素转u32合并损失5%，然后比直接2层循环再少20%(用u32的时候只再差4%)，很奇怪，我怀疑和编译器优化或者机器指令集有关系，我一会儿把设备的信息也发一下

2024-12-25 13:44 UTC, Nugine commented
![图片](https://github.com/user-attachments/assets/5663b636-c64e-43a4-aa5e-26bec825374e)

OS: Ubuntu 22.04.5 LTS
CPU: 13th Gen Intel® Core™ i9-13900H × 20
Rust: rustc 1.83.0 (90b35a623 2024-11-26)

2024-12-25 14:10 UTC, Nugine commented
看起来我的写法可以触发自动向量化，所以获得了大幅性能提升

https://github.com/pacak/cargo-show-asm
```
RUSTFLAGS='-C target-cpu=native' cargo asm --rust --lib  -- zuc::eia3_128::generate_mac
```

![图片](https://github.com/user-attachments/assets/4c8d2884-2eda-4148-8b9a-bf17f5feaf1e)

2024-12-26 06:29 UTC, Nugine commented
由于发现 SIMD 优化空间，现在我们不再对此 PR 要求优化，在 O(1) 空间的基础上通过 5 个标准测试用例和 2 个追加测试用例即可合并。

2024-12-26 08:31 UTC, Xerxes-zhz commented
OS: Linux my-host-0 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (虚拟机分了16核, 64G内存)
Rust: rustc 1.83.0 (90b35a623 2024-11-26)

OK, 那我就不研究了, 在看到你这边的通知之前, 我按我这边的做法实现了整个流程并做了一系列测试, 我现在认为之前的我这边的方案的性能提升主要是在特定测例下, 且其他部分没有触发编译器优化的, 其他部分优化不足的情况下, 不合并确实快, 但优化到位时, 会触发编译器优化, 此时合并4字节更快, 目前用最新的测例在我的机器上, 不合并比合并要慢4%左右

![image](https://github.com/user-attachments/assets/dc0b7cbb-abcc-459b-bb0c-91f19108387c)

2024-12-26 09:38 UTC, Nugine commented
OK 其他机器的测试结论也很有价值。

我试验了手写 SIMD 优化，基线为当前 PR 最新提交，采用 `RUSTFLAGS='-C target-cpu=native'` 编译，加速比约为 +155%。由于 SIMD 代码有比较重的维护负担，这个等以后再进主线。

目前阶段的要求是
+ 修改代码以通过所有测试
+ 保持 O(1) 空间的属性

2024-12-26 15:40 UTC, Nugine approved these changes

2024-12-26 15:40 UTC, merged